require_relative '../../src/exceptions.rb'
require_relative '../../src/fixed_array.rb'
require_relative '../../src/array_list.rb'
require_relative '../../src/linked_list.rb'
require_relative '../../src/node.rb'
# require_relative '../../src/queue.rb'
# require_relative '../../src/stack.rb'
# require_relative '../../src/tree_list.rb'
# require_relative '../../src/tree_node.rb'
# require_relative '../../src/tree.rb'
# require_relative '../../src/set.rb'
# require_relative '../../src/hash.rb'
