require_relative '../../lib/exceptions.rb'
require_relative '../../lib/fixed_array.rb'
require_relative '../../lib/array_list.rb'
require_relative '../../lib/linked_list.rb'
require_relative '../../lib/node.rb'
# require_relative '../../lib/queue.rb'
# require_relative '../../lib/stack.rb'
# require_relative '../../lib/tree_list.rb'
# require_relative '../../lib/tree_node.rb'
# require_relative '../../lib/tree.rb'
# require_relative '../../lib/set.rb'
# require_relative '../../lib/hash.rb'
